# Generated by Django 4.1.4 on 2022-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
