# Generated by Django 4.1.4 on 2022-12-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_card_cprice_card_cstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cid',
        ),
    ]
