# Generated by Django 4.1.4 on 2022-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_card_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cpicture',
            field=models.CharField(default='default_picture', max_length=1000),
        ),
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
    ]
